### PR TITLE
[FIX] warehouse should not be a search criteria to find moves

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
When stock moves are created, that do not specifically include the warehouse, those moves are not detected by the stock planning module to compute incoming quantities from moves.

Reviewed with Anna yesterday.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why stock moves don't include warehouse? Can you tell me which flow leads to this?

**Comment by JordiBForgeFlow** [comment]
This is related to an option that we were exploring with @anajuaristi by which exploding a BOM in the procurement plan should generate stock reservations for the components that need to be procured in advance, so that the stock plan correctly reflects the stock in each period.

We were using the module 'stock_reserve' (https://github.com/OCA/stock-logistics-warehouse/tree/8.0/stock_reserve) to generate stock reservations. These reservations involve stock moves that do not include the warehouse.

**Comment by pedrobaeza** [comment]
Uhm, I'm not sure this can be an allowed data state, but I let @anajuaristi to say.

**Comment by anajuaristi** [comment]
Stock moves are related to location not to warehouse.
Including warehouse in moves selection is making wrong the selected dataset so I :+1: to correction.
Otherwise stock_planning is not calculating correctly "incoming material" and "outgoing material". 
About the stock_reserve is totally independent subject. Nothing to see with the bug caused by including warehouse on select condition.

**Comment by alfredoavanzosc** [comment]
@pedrobaeza , ¿puedes hacer el merge de esto por favor?, tengo que modificar cosas que me ha solicitado Ana.

**Pull request merged**
